main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story7/urls.py
from django.urls import path

from . import views
app_name = 'story7'

urlpatterns =[
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path

from . import views
app_name = 'story8'

urlpatterns =[
    path('', views.story8, name='story8'),
    path('data', views.data, name='data'),
]

story9/urls.py
from django.urls import path

from . import views
app_name = 'story9'

urlpatterns =[
    path('', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('logout/', views.logout_page, name='logout') 
]

storylagi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
]

main/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

story9/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password_first = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_again = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = self.cleaned_data.get('password_first')
        password_two = self.cleaned_data.get('password_again')
        if password_one != password_two:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if qs.exists():
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story7/views.py
from django.shortcuts import render

# Create your views here.

def story7(request):
    return render(request, 'story7.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def story8(request):
    response = {}
    return render(request, 'story8.html', response)

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from .models import Profile
from .forms import LoginForm, RegisterForm


User = get_user_model()

def login_page(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form
    }
    print(request.user.is_authenticated)
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            print("error!")

    return render(request, "login.html", context=context)

def register_page(request):
    form = RegisterForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password_first")
        User.objects.create_user(username, email, password)
        return redirect("/story9")
    return render(request, "register.html", context=context)

def logout_page(request):
    logout(request)
    return render(request, 'main/home.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story Tsanaa</title>
{% endblock meta %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    {% if user.is_authenticated %}
    <h1 class="display-4">Hello, {{user.username}}!</h1>
    {% else %}
    <h1 class="display-4">Hello!</h1>
    {% endif %}
    <p class="lead">This is my website.</p>
    <hr class="my-4">
    <p>Wanna see my stories?</p>
    <a class="btn btn-primary btn-info" href="{% url 'story7:story7' %}" role="button">Story7</a>
    <a class="btn btn-primary btn-info" href="{% url 'story8:story8' %}" role="button">Story8</a>
  </div>
</div>
{% endblock content %}

story7/templates/story7.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story Tsanaa</title>

{% endblock meta %}
   
{% block content %} 

<div class="container accor">
    <div id="accordionActivity">
        <h3>Aktivitas 
            <span style="float: right;">
              <button style='font-size:15px' class="button-up"><i class='fas fa-angle-up'></i></button>
              <button style='font-size:15px' class="button-down"><i class='fas fa-angle-down'></i></button>
            </span>
        </h3>
        <div>
          <ul>
            <li>Kuliah</li>
            <li>Nonton drakor</li>
            <li>Nugas</li>
          </ul>
        </div>
    </div>
    
    <div id="accordionPanit">
      <h3>Pengalaman Organisasi/Kepanitiaan
        <span style="float: right;">
          <button style='font-size:15px' class="button-up"><i class='fas fa-angle-up'></i></button>
          <button style='font-size:15px' class="button-down"><i class='fas fa-angle-down'></i></button>
        </span>
      </h3>
      <div>
        <ul>
          <li>Humas dan Publikasi Wisgan 2020</li>
          <li>Digital Marketing Compfest 2020</li>
          <li>Relasi Wisgen 2020</li>
          <li>Dankom OH Fasilkom 2020</li>
        </ul>
      </div>
    </div>

    <div id="accordionPrestasi">
      <h3>Prestasi 
        <span style="float: right;">
          <button style='font-size:15px' class="button-up"><i class='fas fa-angle-up'></i></button>
          <button style='font-size:15px' class="button-down"><i class='fas fa-angle-down'></i></button>
        </span>
      </h3>
      <div>
        <ul>
          <li>Mendapatkan nilai 100 di Ujian Nasional Bahasa Inggris</li>
          <li>Menang lomba tari waktu SD</li>
        </ul>
      </div>
    </div>

    <div id="accordionHobi">
      <h3>Hobi 
        <span style="float: right;">
          <button style='font-size:15px' class="button-up"><i class='fas fa-angle-up'></i></button>
          <button style='font-size:15px' class="button-down"><i class='fas fa-angle-down'></i></button>
        </span>
      </h3>
      <div>
        <ul>
          <li>Nonton film, drakor, dan series</li>
          <li>Dengerin lagu</li>
          <li>Makan</li>
        </ul>
      </div>
    </div>
</div>
{% endblock content %} 

story8/templates/story8.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story Tsanaa</title>
{% endblock meta %}

{% block content %}

<div class="container search">
    <br>
    <h3 class = "mt-5" style="text-align: center; margin-top: 100px;">Daftar Buku</h1>
    <div class="container justify-content-center text-center p-5" style="max-width: 500px;">
        <input class="form-control" id="keyword" type="text" placeholder="Masukkan judul buku!" aria-label="Search">
    </div>
</div>      

<div class="container">
    <table class="table table-bordered table-striped table-info">
        <thead>
            <tr>
                <th scope="col">Buku</th>
                <th scope="col">Judul</th>
                <th scope="col">Penulis</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
{% endblock content %}

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story Tsanaa</title>
{% endblock meta %}

{% block content %}
<br><br>
<div class="container">
    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <form method="POST">

                {% csrf_token %}
                {{ form.as_p }}
            
                <button type="submit" class="btn btn-primary">Login</button>
            
            </form>
        </div>
    </div>
    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <h5 style="color: black;">Don't have an account? <a href="{% url 'story9:register'%}">Register</a></h5>
        </div>        
    </div>
</div>
{% endblock content %}

story9/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story Tsanaa</title>
{% endblock meta %}

{% block content %}
<div class="row m-5 justify-content-center">
  <div class="col text-center">
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <h5 style="color: black;" {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </h5>
          {% endfor %}
      </ul>
      {% endif %}     
  </div>
</div>

<div class="row m-5 justify-content-center">
  <div class="col-md-8 col-sm-8">
      <form method="POST">

          {% csrf_token %}
      
          {{ form.as_p }}
      
          <button type="submit" class="btn btn-primary">Register</button>
      
      </form>
  </div>        
</div>
<div class="row m-5 justify-content-center">
  <div class="col-md-8 col-sm-8">
      <h5 style="color: black;">Already have an account? <a href="{% url 'story9:login'%}">Login</a></h5>
  </div>   
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS Script -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="{% static 'jquery-3.5.1.js' %}"></script>
    <script src="{% static 'story7.js' %}"></script>
    <script src="{% static 'story8.js' %}"></script>

    {% block meta %}
    {% endblock meta %}
    <title>Storynya Tsanaa</title>
</head>
  
  <!--Bootstrap Navbar-->
  <body>
    <header class="header fixed-top">
      <nav class="navbar navbar-expand-lg sticky-top navbar-light">
        <div class="container">
          <a class="navbar-brand " href="{% url 'main:home' %}"><strong>TSANAA</strong></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <a class="nav-link">{{user.username}}</a>
                <a class="nav-link" href="{% url 'story9:logout' %}">Logout</a>
              {% else %}
                <a class="nav-link" href="{% url 'story9:login' %}">Login</a>
                <a class="nav-link" href="{% url 'story9:register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
  
    
  
    {% block content %}
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% endblock content %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </body>
  </html>